services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - traces_data:/app/traces
    environment:
      - TRACES_DB_PATH=${SQLITE_TRACES_DB} # <-- add this
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AI_MODEL=${AI_MODEL}
      - SQLITESEARCHDB=${SQLITESEARCHDB}
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
      - CHROMA_DB_DIR=${CHROMA_DB_DIR}
      - CHROMA_TEST_COLLECTION=${CHROMA_TEST_COLLECTION}
      - CHROMA_DB_TEST_DIR=${CHROMA_DB_TEST_DIR}
      - MODEL_BASE_URL=${MODEL_BASE_URL}
      - DATA_FILE_PATH=${DATA_FILE_PATH}
      - DATA_TEST_FILE_PATH=${DATA_TEST_FILE_PATH}
      - DATA_EVAL_ANSWER_FILE_PATH=${DATA_EVAL_ANSWER_FILE_PATH}
      - DATA_PATH_FOLDER=${DATA_PATH_FOLDER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}

    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      grafana:
        condition: service_started

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  traces_data:
  grafana_data:
